#### Agregaciones
Siempre se va a calcular las estadisticas, entre ellas están la media, la desviacion estandar, suma, mediana, minimo, maximo entre otros.

#### Suma de los valores de una matriz

In [2]:
import numpy as np
list=np.array([1,2,3,1,3,5,3,5,77,5,4,3,23,2,3])
print(np.sum(list))

140


### Min y Máx

In [3]:
print(np.min(list))
print(np.max(list))

1
77


#### Agregados multidimencionales

In [5]:
md = np.random.random((3, 4))
print(md)
md.sum() #Suma tooodos los valores

[[0.52114569 0.55256857 0.42875619 0.14069558]
 [0.13746716 0.11301812 0.86690731 0.09040527]
 [0.43634274 0.61086684 0.69055899 0.99712766]]


5.58586011490424

Las funciones de agregación toman un argumento adicional que especifica el eje a lo largo del que se calcula la agregación. Por ejemplo, se puede buscar el valor mínimo dentro de cada columna si se especifica axis=0:
axis especifica la dimensión de la matriz que se va a contraer

In [9]:
print(md.min(axis=0))#minimo numero por cada columna(variable) de la matriz
print(md.min(axis=1))#minimo numero por cada fila(registro) de la matriz
print(md.max(axis=0))#maximo numero por cada columna(variable) de la matriz
print(md.max(axis=1))#maximo numero por cada fila(registro) de la matriz

[0.13746716 0.11301812 0.42875619 0.09040527]
[0.14069558 0.09040527 0.43634274]
[0.52114569 0.61086684 0.86690731 0.99712766]
[0.55256857 0.86690731 0.99712766]


np.sum	np.nansum	Calcula la suma de los elementos

np.prod	np.nanprod	Calcula el producto de los elementos

np.mean	np.nanmean	Calcula el promedio de los elementos

np.std	np.nanstd	Calcula la desviación estándar

np.var	np.nanvar	Calcula la varianza

np.min	np.nanmin	Busca el valor mínimo

np.max	np.nanmax	Busca el valor máximo

np.argmin	np.nanargmin	Busca el índice del valor mínimo

np.argmax	np.nanargmax	Busca el índice del valor máximo

np.median	np.nanmedian	Calcula la mediana de los elementos

np.percentile	np.nanpercentile	Calcula estadísticas basadas en clasificaciones de los elementos

np.any	No aplicable	Evalúa si alguno de los elementos es true

np.all	No aplicable	Evalúa si todos los elementos son true