### Difusión en matrices
**Reglas de difusión**
La difusión sigue un conjunto de reglas para determinar la interacción entre dos matrices:

**Regla 1:** si las dos matrices difieren en el número de dimensiones, la forma de la que tiene menos dimensiones se rellena con unos en su lado inicial (el izquierdo).

**Regla 2:** si la forma de las dos matrices no coincide en ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se extiende para que coincida con la otra forma.

**Regla 3:** si, en cualquier dimensión, los tamaños no coinciden y ninguno es igual a 1, NumPy genera un error.

In [3]:
import numpy as np
horizontal_array = np.arange(3)
vertical_array = np.arange(3)[:, np.newaxis]

print(horizontal_array)
print(vertical_array)
horizontal_array + vertical_array

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [6]:
two_dim_array = np.ones((2, 3))
one_dim_array = np.arange(3)
print(two_dim_array)
print(two_dim_array.shape)
print(one_dim_array)
print(one_dim_array.shape)
two_dim_array + one_dim_array

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[0 1 2]
(3,)


array([[1., 2., 3.],
       [1., 2., 3.]])

### Ejemplo 2

In [9]:
vertical_array = np.arange(3).reshape((3, 1))
print(vertical_array)
horizontal_array = np.arange(3)
print(horizontal_array)
vertical_array + horizontal_array


[[0]
 [1]
 [2]]
[0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Practica

In [10]:
T = np.random.random((10, 3))
T

array([[0.21764466, 0.3224898 , 0.49285608],
       [0.84495459, 0.89842385, 0.98647683],
       [0.23221854, 0.21083928, 0.96172544],
       [0.60184934, 0.72944122, 0.28957288],
       [0.14150013, 0.01298465, 0.8769569 ],
       [0.87796013, 0.228217  , 0.58608088],
       [0.53262039, 0.80560551, 0.92285682],
       [0.10194044, 0.05674555, 0.46489143],
       [0.43806665, 0.80105995, 0.93653   ],
       [0.37280295, 0.61341773, 0.22489108]])

### Media en cada columna o variable

In [15]:
Tmean = T.mean(0)
Tmean

array([0.43615578, 0.46792245, 0.67428383])

In [16]:
#Difusion
T_centered = T - Tmean
T_centered

array([[-0.21851112, -0.14543266, -0.18142776],
       [ 0.40879881,  0.43050139,  0.312193  ],
       [-0.20393724, -0.25708317,  0.28744161],
       [ 0.16569356,  0.26151877, -0.38471096],
       [-0.29465565, -0.45493781,  0.20267307],
       [ 0.44180435, -0.23970545, -0.08820296],
       [ 0.09646461,  0.33768306,  0.24857299],
       [-0.33421534, -0.4111769 , -0.2093924 ],
       [ 0.00191086,  0.3331375 ,  0.26224617],
       [-0.06335283,  0.14549527, -0.44939276]])