##### Importamos la libreria de numpy (numeric-Python)

In [1]:
import numpy as np

##### Cuando se trabaja con las matrices o vectores de numpy se tiene una optimización en cuanto a almacenamiento de memoria dado a que en una lista normal todo el contenido de ella es un objeto distinto, y en un np.array todo el vector por completo es un objeto unico, se ahorra mucho espacio de memoria

In [9]:
vectorcito=np.array([1,2,3,4,5,6,7,8,9,10])
type(vectorcito)


numpy.ndarray

##### Si intentamos conbinar tipos de datos distintos dentro de un arreglo, numpy intentara convertir todo a un mismo tipo

In [11]:
vectorcito=np.array([1.43,5,'washawasha',True])
print(vectorcito)

['1.43' '5' 'washawasha' 'True']


##### Podemos obligar a nuestro vector a que sea de un determinado tipo de dato

In [12]:
vectorcito=np.array([1.23,2.34,332.43], dtype='int32')
print(vectorcito)

[  1   2 332]


##### Crear matrices y vectores desde cero

In [14]:
matriz3x4=np.ones((3,4),dtype='float') #3 filas y 4 columnas
print(matriz3x4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### para ceros igual

In [15]:
Matriz0=np.zeros((3,4),dtype='float') #3 filas y 4 columnas
print(Matriz0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Si queremos que toda la matriz este multiplicada por un num

In [18]:
vectorcito=np.full((3,2),54)
print(vectorcito)

[[54 54]
 [54 54]
 [54 54]]


##### Matrices rellenadas con una secuencia lineal

In [19]:
vector=np.arange(0,10,2)#crea un vector de 0 a 10 con pasos de 2
print(vector)

[0 2 4 6 8]


### vectores espaciados uniformemente

In [24]:
matriz=np.linspace(0,10,2) #vector espaciado uniformemente entre 0 y 10 en cantidad de 5 veces
print(matriz)

[ 0. 10.]


###### Matriz 3x3 con valores aleatorios

In [25]:
matricita=np.random.random((3,4)) #matriz de 3 filas y 4 columnas con numeros aleatorios
print(matricita)

[[0.45308666 0.79593692 0.86674489 0.92018903]
 [0.15356482 0.5939364  0.58221567 0.99951771]
 [0.7091693  0.85161905 0.98684125 0.02595622]]


#### Matriz de 3x3 con valores aleatorio y desviacion estandar de 1

In [26]:
np.random.normal(0, 1, (3, 3))

array([[-1.47307593, -0.10800565, -1.2889411 ],
       [-0.28991063,  0.95900847,  1.38232943],
       [-0.07937717,  0.03389465,  0.93032571]])

##### Matriz identidad 3x3

In [30]:
np.eye(2) #matriz identidad

array([[1., 0.],
       [0., 1.]])

#### Funciones de numpy para crear matrices

**array** Convierte los datos de entrada (lista, tupla, matriz u otro tipo de secuencia) en un objeto ndarray, ya sea mediante la inferencia de un valor dtype o la especificación explícita de un valor dtype. Copia los datos de entrada de forma predeterminada.

**asarray**	Convierte la entrada en un objeto ndarray pero no copia si la entrada ya es un objeto ndarray.

**arange**	Es similar a la función range() integrada, pero devuelve un objeto ndarray en lugar de una lista.

**ones, ones_like**	ones genera una matriz de unos con la forma y el valor dtypeespecificados. 
ones_like toma otra matriz y genera una matriz de unos de la misma forma y dtype.

**zeros, zeros_like**	Similar a ones y ones_like, pero que genera matrices de ceros en su lugar.

**empty, empty_like**	Cree nuevas matrices mediante la asignación de memoria nueva, pero no rellene con valores como hacen ones y zeros .
**full, full_like**	full genera una matriz con la forma y el valor dtype especificados, con todos los valores establecidos en el "valor de relleno" indicado.
full_like toma otra matriz y genera una matriz rellenada con la misma forma y dtype.

**eye, identity**	Cree una matriz de identidad N x N cuadrada (unos en la diagonal y ceros en el resto).

In [36]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='float')
print(arr)
arr2=np.asarray([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
range=np.arange(10,100,10.1)
print(range)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[10.  20.1 30.2 40.3 50.4 60.5 70.6 80.7 90.8]
