#### Uso de matrices booleanas

In [5]:
#Matriz de dos dimensiones
import numpy as np
two_dim_matrix =np.random.randint(0,10(3,3))
print(two_dim_matrix)

[[2 7 6]
 [7 8 4]
 [2 7 9]]


## ¿Cuantos valores son menores que 6?

In [7]:
np.count_nonzero(two_dim_matrix < 6) #False se interpreta como 1 y True como 0
np.sum(two_dim_matrix < 6) #Suma de los elementos menores a 6 False como 0 y True como 1

3

##### La ventaja de sum es que se puede usar para filas como para cada columna

In [11]:
print(f"Columas: {np.sum(two_dim_matrix < 6, axis = 0)} \n") #Suma de los elementos mayores a 6 en cada columna
print(f"Filas: {np.sum(two_dim_matrix < 6, axis = 1)} ") #Suma de los elementos mayores a 6 en cada fila

Columas: [2 0 1] 

Filas: [1 1 1] 


### ¿Hay algun valor menor que 6?

In [13]:
np.any(two_dim_matrix<6) #True si algun elemento es menor a 6

True

### Operadores Logicos
&	np.bitwise_and

|	np.bitwise_or

^	np.bitwise_xor

~	np.bitwise_not

### Matrices Booleanas como mascaras

In [15]:
two_dim_matrix

array([[2, 7, 6],
       [7, 8, 4],
       [2, 7, 9]])

In [16]:
# Obteniendo una matriz booleana de todos los valores menores a 5
two_dim_matrix < 5

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False]])

In [17]:
# Indexar una matriz booleana por la condicion de menores a 5 (ennascaramiento)
two_dim_matrix[two_dim_matrix < 5]

array([2, 4, 2])

In [ ]:
# Construct a mask of all rainy months
rainy = (rainfall_2003 > 0)

# Construct a mask of all summer months (June through September)
months = np.arange(1, 13)
summer = (months > 5) & (months < 10)

print("Median precip in rainy months in 2003 (inches):   ",
      np.median(rainfall_2003[rainy]))
print("Median precip in summer months in 2003 (inches):  ",
      np.median(rainfall_2003[summer]))
print("Maximum precip in summer months in 2003 (inches): ",
      np.max(rainfall_2003[summer]))
print("Median precip in non-summer rainy months (inches):",
      np.median(rainfall_2003[rainy & ~summer]))