#### np.sort para devolver versión ordenada de una matriz sin modificar la entrada

In [10]:
import numpy as np
a=np.array([2,99,5,1,3])
a.sort()#Ordena los numeros de menor a mayor
np.sort(a)#Ordena los numeros de menor a mayor

array([ 1,  2,  3,  5, 99])

### argsort devuelve los indices

In [13]:
a = np.array([2, 1, 4, 3, 5])
b = np.argsort(a)
print(b)

print(a[b])


[1 0 3 2 4]
[1 2 3 4 5]


#### Ordenación por filas o columnas por el metodo axis

In [14]:
rand = np.random.RandomState(42)
table = rand.randint(0, 10, (4, 6))
print(table)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [17]:
np.sort(table, axis=0) #ordena cada columna

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [18]:
np.sort(table, axis=1) #ordena cada fila

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

#### Partition con numpy

In [26]:
arr = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(arr, 3)#los tres primeros valores son los mas pequeños los elementos tiene un orden arbitrario

array([2, 1, 3, 4, 6, 5, 7])

In [27]:
np.partition(table, 2, axis=1)#Los primeros 2 valores de cada fila son los más pequeños

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])