### Atributos de matrices

In [14]:
import numpy as np
np.random.seed(0)  # Seed for reproducibility

a1 = np.random.randint(10, size=6)  # One-dimensional array
a2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
a3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

##### Cada matriz tiene sus propios atributos:
**ndim**: numero de dimensiones de una matriz 

**shape**: tamaño de cada dimension de la matriz

**size**: Numero total de elementos d ela matriz

In [15]:
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[5 0 3 3 7 9]
1
(6,)
6


In [16]:
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
2
(3, 4)
12


In [17]:
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
3
(3, 4, 5)
60


#### Indexación de matrices

In [29]:
print(a1)
print(a1[0:4])
print(" ")
print(a2)
print(a2[2, 0:2])
print(a2[2,3])
print(" ")
print(a3)
print(a3[0, 0, 0:5])


[5 0 3 3 7 9]
[5 0 3 3]
 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[1 6]
7
 
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
[8 1 5 9 8]


In [34]:
a1[0]=1
a1

array([1, 0, 3, 3, 7, 9])

In [37]:
a2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
a2[:3,:3]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

### modificar valores de matrices y vista de matrices
al modificar el valor de una vista de matriz se modifica el valor de la matriz, esta directamente vinculado

Para evitar eso se puede crear una nueva copia de la matriz con el metodo copy()

In [45]:
print(a2)
a2_sub=a2[:3,:3]
print(f"\n{a2_sub}")
a2_sub[0,0]=100
print(f"\n{a2_sub}")
print(f"\n{a2}")

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

[[3 5 2]
 [7 6 8]
 [1 6 7]]

[[100   5   2]
 [  7   6   8]
 [  1   6   7]]

[[100   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


#### Remodelacion de matrices
cambiar sus dimenciones

In [52]:
grid=np.arange(1,10)
print(f" \n {grid.reshape(3,3)}")
grid2=grid[:,np.newaxis] #Tenemos un vector de 1 row (grid) le añadimos un nuevo eje (np.newaxis) para cambiarlo a columna
print(f" \n {grid2}")


 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


#### Combinar dos o mas conjunto de valores 

In [60]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate([a,b])

a1=np.array([[1,2,4,5],[1,2,3,4]])
a2=np.array([[9,8,7,6],[2,3,4,64]])
b2=np.concatenate([a1,a2],axis=1)
print(f"\n{b2}")


[[ 1  2  4  5  9  8  7  6]
 [ 1  2  3  4  2  3  4 64]]


##### División de matrices
np.split()

In [70]:
a = [1, 2, 3, 99, 99, 3, 2, 1]
a1, a2, a3 = np.split(a, [3, 5]) #de 3 a 5 se almacenan en a2
print(a1, a2, a3)

[1 2 3] [99 99] [3 2 1]


#### Indexación avanzada
se puede acceder a varios valores de una matriz unidimensional dandole un indice

In [72]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
ind=[0,4,-1]
print(arr[ind])

[ 1  5 10]


Mismo caos para volverlo en forma de matriz

In [76]:
print(f"{arr} \n")
ind=np.array([[0,-1],
             [4,5]])
print(arr[ind])

[ 1  2  3  4  5  6  7  8  9 10] 

[[ 1 10]
 [ 5  6]]


### Esto también funciona para matrices de 2 o más dimensiones

In [79]:
arr2 = np.arange(12).reshape((3, 4))
print(f"{arr2} \n")
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
arr2[row, col] # a cada valor de row le equivale un valor de col [0,2] [1,1] [2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



array([ 2,  5, 11])

In [80]:
arr2[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

#### Combinacion de indices avanzados y simples


In [83]:
print(arr2)
arr2[2,[1,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 9, 11])

## Modificacion de valores mediante la indexación avanada

In [87]:
arr = np.arange(10)
ind = np.array([0,4])
arr[ind] = 99
print(ind)

[99  1  2  3 99  5  6  7  8  9]


In [90]:
ind = np.zeros(10)
ind[[0, 0]] = [4, 6]
print(ind)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
